# Generated by Django 5.0.6 on 2025-01-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0008_parkingticket_exit_time_parkingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingticket',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
