# Generated by Django 5.0.6 on 2025-01-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0011_branch_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('MANAGER', 'Manager')], default='ADMIN', max_length=50),
        ),
    ]
