# Generated by Django 5.0.6 on 2025-02-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0012_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='client',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('MANAGER', 'Manager')], default='MANAGER', max_length=50),
        ),
    ]
