# Generated by Django 5.0.6 on 2025-02-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0016_parkingticket_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingticket',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='parkingticket',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
