# Generated by Django 5.0.6 on 2025-02-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0017_remove_parkingticket_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingticket',
            name='payment_status',
        ),
    ]
