# Generated by Django 5.0.6 on 2025-02-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0018_remove_parkingticket_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingticket',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
