# Generated by Django 5.0.6 on 2025-02-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0020_expenditure_item_name_expenditure_price_per_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='payment_method',
        ),
    ]
