# Generated by Django 5.0.6 on 2025-02-20 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0021_remove_cart_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_branches', models.BooleanField(default=False)),
                ('can_issue_tickets', models.BooleanField(default=False)),
                ('can_register_clients', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
