# Generated by Django 5.0.6 on 2025-02-21 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0022_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userpermission', to=settings.AUTH_USER_MODEL),
        ),
    ]
