# Generated by Django 5.0.6 on 2025-02-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0023_alter_userpermission_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
