# Generated by Django 5.0.6 on 2025-02-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0025_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
