# Generated by Django 5.0.6 on 2025-02-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0027_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='number_of_slots',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='parking_slot_identifier',
            field=models.CharField(default='B', max_length=1),
        ),
    ]
