# Generated by Django 5.0.6 on 2025-02-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0029_client_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
    ]
