# Generated by Django 5.0.6 on 2025-03-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingMangtApp', '0032_cart_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
    ]
